fix(include): We need a pointer without const for mocking
cmocka.h:522:6: error: cast discards ‘const’ qualifier from pointer
target type [-Werror=cast-qual]
    ((type)(_mock(__func__, __FILE__, __LINE__, NULL)).ptr)
     ^

(cherry picked from commit 8a20800711d5e521d41786840961515460e1fc75)